---

- name: Download samtools
  get_url:
    url=https://github.com/samtools/samtools/archive/{{version}}.tar.gz
    dest={{source_dir}}/samtools-{{version}}.tar.gz

- name: Uncompress samtools
  unarchive: 
    src: "{{ source_dir }}/samtools-{{version}}.tar.gz"
    dest: "{{ source_dir }}"
    copy: no
    creates: "{{ source_dir }}/samtools-{{version}}/README"

- name: Build and Install samtools
  shell: cd {{ source_dir }}/samtools-{{version}}; make install prefix="{{ soft_dir }}/samtools-{{version}}" HTSDIR="../htslib-{{htslib_version}}"
  args:
    creates: "{{ soft_dir }}/samtools-{{version}}/bin/samtools"

- name: Set samtools globaly
  become: "{{ bool_var }}"

  file:
    path: /usr/local/bin/samtools
    src: "{{ soft_dir }}/samtools-{{ version }}/bin/samtools"
    state: link
    owner: "{{ main_guy }}"
  when: "{{ bool_var }}"

  tags: samtools
